version: "3.9"
services:
  api:
    container_name: "api_producao"
    image: api_producao:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "80:80"
      - "9000:80"
    volumes:
      - ".:/var/www/html"
      - "./docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro"
    networks:
      - producao_api
      - producao_mysql
      - producao_redis
  mysql:
    container_name: "api_mysql"
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - "producao_mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - producao_mysql
  redis:
    container_name: "api_redis"
    image: redis:6.0.9-alpine3.12
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: "no"
    ports:
      - "6379:6379"
    volumes:
      - "producao_redis:/data"
    networks:
      - producao_redis
networks:
  producao_api:
  producao_mysql:
  producao_redis:
volumes:
  producao_mysql:
  producao_redis: